### ISSUE TITLE
Price json not parsable by Home Assistant

### ISSUE THREAD

**Issue by ujhede** [gskjold/AmsToMqttBridge#206]
I think beginning from 2.0.3 it looks like Home Assistant is unable to parse the json received in the price message.

I don't see the messages received in the mosquito subscribe to topic window and in the HA logs i see the error below.

Error from 2.0.5.

1. Configure MQTT and valid ENTSO E API connection to Home Assistant mosquito adding.
2. In HA go to MQTT setting and type topic in "Listen to topic" press start listen.
3.  Watch for the messages that includes future prices.

**Expected behavior**
Message should be received in HA

**Screenshots**

**Hardware information:**
 - Meter:  Kamstrup Danish
 - AMS reader:  ESP32 D1 Clone
 - M-bus adapter (if applicable):

**Relevant firmware information:**
 - Version:  2.0.5
 - MQTT: Yes
 - HAN GPIO: 16
 - HAN baud and parity:  2400 8N1
 - Temperature sensors [e.g. 3xDS18B20]

**Additional context**

From HA logs when receiving the price messges via MQTT

ERROR (MainThread) [homeassistant.util.logging] Exception in attributes_message_received when handling msg on 'kamstrup': '{"id":"8C:AA:B5:8B:80:C8","prices":{"0":12.2619,"1":12.1279,"2":12.9469,"3":12.8575,"4":13.0362,"5":17.8457,"6":22.9604,"7":17.8382,"8":14.4359,"9":13.3712,"10":13.6541,"11":12.8054,"min":9.8274,"max":22.9604,"cheapest1hr":"2022-01-16T22:00:00Z","cheapest3hr":"2022-01-16T20:00:00Z","cheapest6hr":"2022-01-16T10:00:00Z"}}'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 37, in wrapper
    msg_callback(msg)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 266, in attributes_message_received
    payload = attr_tpl.async_render_with_possible_json_value(payload)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 569, in async_render_with_possible_json_value
    return _render_with_context(
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1771, in _render_with_context
    return template.render(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.9/site-packages/jinja2/filters.py", line 1673, in do_tojson
    return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/jinja2/utils.py", line 736, in htmlsafe_json_dumps
    dumps(obj, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type LoggingUndefined is not JSON serializable

**Comment by gskjold** [comment]
Guessing this is a HA problem. Price JSON have not changed for months and the JSON in your log above checks out.
