### ISSUE TITLE
Exception in async_discover

### ISSUE THREAD

**Issue by MikOsle** [gskjold/AmsToMqttBridge#272]
**Describe the bug**
I'm getting following error message in HA.

2022-05-02 22:17:18 INFO (MainThread) [homeassistant.components.mqtt.discovery] Found new component: sensor kamstrup-meter
2022-05-02 22:17:18 ERROR (MainThread) [homeassistant.util.logging] Exception in async_discover when dispatching 'mqtt_discovery_new_sensor_mqtt': ({'id': '40:F5:20:25:52:40', 'name': 'el-maaler', 'up': 3446, 'topic': 1651522620, 'vcc': 3.219, 'rssi': -69, 'temp': -127.0, 'data': {'lv': '', 'id': '', 'type': '', 'P': 241, 'Q': 0, 'PO': 0, 'QO': 241, 'I1': 0.15, 'I2': 0.97, 'I3': 0.68, 'U1': 230.0, 'U2': 231.0, 'U3': 231.0, 'PF': 0.7, 'PF1': 0.11, 'PF2': 0.71, 'PF3': 0.8, 'tPI': 11197.76, 'tPO': 0.0, 'tQI': 711.88, 'tQO': 4758.5, 'rtc': 1651522620}, 'realtime': {'h': 0.08, 'd': 6.8, 't': 5, 'x': 0.93}, 'platform': 'mqtt'},)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 246, in async_discover
    config = schema(discovery_payload)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 218, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 341, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 337, in _exec
    v = func(v)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: required key not provided @ data['state_topic']

**Hardware information:**
 - Meter: Kamstrup
 - AMS reader: ESP8266, D1 mini

**Relevant firmware information:**
 - Version: 2.1.2
 - MQTT: yes
 - HAN GPIO: UART2 (GPIO13)
 - HAN baud and parity: 2400 8N1

**Comment by ArnieO** [comment]
Ping @aadnehovda @bardahlm @kng @svhaaland

**Comment by kng** [comment]
That message does not look like it's coming from hadiscover.json, rather json1.json.
So, the payload was set to home-assistant, then back to json?
Please share a screendump of the mqtt settings.
The discovery topic should probably have a remove button in the webui, to remove the retains and clear the content so HA forgets the sensor.

**Comment by MikOsle** [comment]
Is this the setting you are asking for?

<img width="593" alt="Skærmbillede 2022-05-03 kl  20 16 38" src="https://user-images.githubusercontent.com/46725638/166517052-605d5e5c-928d-4f68-8f96-ec2fe875b213.png">
<img width="582" alt="Skærmbillede 2022-05-03 kl  20 16 53" src="https://user-images.githubusercontent.com/46725638/166517057-62a3bb35-152b-4774-b5de-4b83f681ea1a.png">

**Comment by kng** [comment]
No, the configuration in the ams reader:
![bild](https://user-images.githubusercontent.com/5262110/166643900-4277e0fe-a799-46d3-9ec3-7998a4a9adeb.png)

Also good to look how the discovery topics look by connecting to the mqtt and subscribing to `homeassistant/sensor/#`

**Comment by MikOsle** [comment]
and here is my MQTT setting on the AMS. 

mqttHost 192.168.###.###
mqttPort 1883
mqttClientId el-maaler
mqttPublishTopic homeassistant/sensor/kamstrup-meter/config
mqttUsername amstomqtt
mqttPassword #####
mqttPayloadFormat 0
mqttSsl 0

**Comment by kng** [comment]
> mqttPublishTopic homeassistant/sensor/kamstrup-meter/config

You are publishing the json payload into the discovery topic.
Put the topic to something outside homeassistant/# and set the payload to Home-Assistant.

**Comment by gskjold** [comment]
Note to self, add to documentation that publishing should happen outside homeassistant topic. Also prevent this in code maybe?

**Comment by MikOsle** [comment]
Hi. Sorry for my late response. After changing the topic it is working perfectly. I am so familiar with this discovery topic thing. 
Thanks!
